"""search, review, claims

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 10:16:00.230757+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_queries",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retrievers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("took_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_search_queries_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_search_queries_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_search_queries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_queries")),
    )
    op.create_index(
        op.f("ix_search_queries_organization_id"),
        "search_queries",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "activity_events",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("activity", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_activity_events_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_activity_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_activity_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_activity_events_site_id_sites"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
    )
    op.create_index(
        op.f("ix_activity_events_organization_id"),
        "activity_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_project_id"), "activity_events", ["project_id"], unique=False
    )
    op.create_table(
        "claims",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "descriptive",
                "progress",
                "outcome",
                "metric",
                name="claimtype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "in_review",
                "approved",
                "rejected",
                "retracted",
                name="claimstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "support_level",
            sa.Enum(
                "unsupported",
                "proposed",
                "reviewed",
                "verified",
                name="supportlevel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("rule_check", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "validation_verdict",
            sa.Enum(
                "supported",
                "partially_supported",
                "not_supported",
                "not_checked",
                name="validationverdict",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_claims_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"], ["users.id"], name=op.f("fk_claims_decided_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_claims_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_claims_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_claims_site_id_sites"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["claims.id"],
            name=op.f("fk_claims_supersedes_id_claims"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
    )
    op.create_index(op.f("ix_claims_organization_id"), "claims", ["organization_id"], unique=False)
    op.create_index("ix_claims_project_status", "claims", ["project_id", "status"], unique=False)
    op.create_table(
        "metrics",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "field_survey",
                "sensor",
                "operational_record",
                "third_party",
                "visual_count",
                name="metricsource",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("source_reference", sa.Text(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_metrics_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_metrics_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_metrics_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_metrics_site_id_sites"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metrics")),
    )
    op.create_index(
        op.f("ix_metrics_organization_id"), "metrics", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_metrics_project_id"), "metrics", ["project_id"], unique=False)
    op.create_table(
        "claim_metrics",
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("metric_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_claim_metrics_claim_id_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["metrics.id"],
            name=op.f("fk_claim_metrics_metric_id_metrics"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_claim_metrics_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_metrics")),
    )
    op.create_index(
        op.f("ix_claim_metrics_organization_id"), "claim_metrics", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_claim_metrics_pair", "claim_metrics", ["claim_id", "metric_id"], unique=True
    )
    op.create_table(
        "embeddings",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("image", "text", name="embeddingkind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_embeddings_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_embeddings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
        sa.UniqueConstraint(
            "asset_id", "kind", "model", name=op.f("uq_embeddings_asset_id_kind_model")
        ),
    )
    op.create_index(op.f("ix_embeddings_asset_id"), "embeddings", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_embeddings_organization_id"), "embeddings", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_embeddings_vector_hnsw",
        "embeddings",
        ["vector"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    op.create_table(
        "search_feedback",
        sa.Column("query_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "click",
                "add_to_evidence",
                "dismiss",
                name="searchfeedbackaction",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_search_feedback_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_search_feedback_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["search_queries.id"],
            name=op.f("fk_search_feedback_query_id_search_queries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_search_feedback_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_feedback")),
    )
    op.create_index(
        op.f("ix_search_feedback_organization_id"),
        "search_feedback",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_search_feedback_query_id"), "search_feedback", ["query_id"], unique=False
    )
    op.create_table(
        "evidence_links",
        sa.Column(
            "target_type",
            sa.Enum("claim", "event", name="evidencetarget", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=True),
        sa.Column(
            "relation",
            sa.Enum(
                "supports",
                "contradicts",
                "context",
                name="evidencerelation",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("span", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(target_type = 'claim' AND claim_id IS NOT NULL AND event_id IS NULL) OR (target_type = 'event' AND event_id IS NOT NULL AND claim_id IS NULL)",
            name=op.f("ck_evidence_links_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_evidence_links_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_evidence_links_claim_id_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_evidence_links_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["activity_events.id"],
            name=op.f("fk_evidence_links_event_id_activity_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_evidence_links_observation_id_observations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_links_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_links")),
    )
    op.create_index("ix_evidence_links_asset", "evidence_links", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_links_organization_id"),
        "evidence_links",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_evidence_links_target", "evidence_links", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "observation_reviews",
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "approve", "reject", "edit", name="reviewdecision", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("previous_status", sa.String(length=20), nullable=False),
        sa.Column("replacement_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_observation_reviews_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_observation_reviews_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_observation_reviews_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replacement_id"],
            ["observations.id"],
            name=op.f("fk_observation_reviews_replacement_id_observations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_observation_reviews_reviewer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation_reviews")),
    )
    op.create_index(
        op.f("ix_observation_reviews_asset_id"), "observation_reviews", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_observation_reviews_observation_id"),
        "observation_reviews",
        ["observation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_reviews_organization_id"),
        "observation_reviews",
        ["organization_id"],
        unique=False,
    )
    op.add_column("assets", sa.Column("search_text", sa.Text(), nullable=True))
    op.add_column(
        "assets",
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(search_text, ''))", persisted=True),
            nullable=True,
        ),
    )
    op.add_column(
        "assets",
        sa.Column("verified_activities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("assets", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("assets", sa.Column("reviewed_by_id", sa.UUID(), nullable=True))
    op.create_index(
        "ix_assets_search_tsv", "assets", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_foreign_key(
        op.f("fk_assets_reviewed_by_id_users"), "assets", "users", ["reviewed_by_id"], ["id"]
    )
    # ### end Alembic commands ###

    # Row-level security for the new tenant tables (same policy as migration 0001).
    for table in [
        "embeddings",
        "search_queries",
        "search_feedback",
        "observation_reviews",
        "metrics",
        "claims",
        "claim_metrics",
        "activity_events",
        "evidence_links",
    ]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting('app.rls_bypass', true) = 'on'
                OR organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid
            )
            WITH CHECK (
                current_setting('app.rls_bypass', true) = 'on'
                OR organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid
            )
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in [
        "embeddings",
        "search_queries",
        "search_feedback",
        "observation_reviews",
        "metrics",
        "claims",
        "claim_metrics",
        "activity_events",
        "evidence_links",
    ]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")

    op.drop_constraint(op.f("fk_assets_reviewed_by_id_users"), "assets", type_="foreignkey")
    op.drop_index("ix_assets_search_tsv", table_name="assets", postgresql_using="gin")
    op.drop_column("assets", "reviewed_by_id")
    op.drop_column("assets", "reviewed_at")
    op.drop_column("assets", "verified_activities")
    op.drop_column("assets", "search_tsv")
    op.drop_column("assets", "search_text")
    op.drop_index(op.f("ix_observation_reviews_organization_id"), table_name="observation_reviews")
    op.drop_index(op.f("ix_observation_reviews_observation_id"), table_name="observation_reviews")
    op.drop_index(op.f("ix_observation_reviews_asset_id"), table_name="observation_reviews")
    op.drop_table("observation_reviews")
    op.drop_index("ix_evidence_links_target", table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_organization_id"), table_name="evidence_links")
    op.drop_index("ix_evidence_links_asset", table_name="evidence_links")
    op.drop_table("evidence_links")
    op.drop_index(op.f("ix_search_feedback_query_id"), table_name="search_feedback")
    op.drop_index(op.f("ix_search_feedback_organization_id"), table_name="search_feedback")
    op.drop_table("search_feedback")
    op.drop_index(
        "ix_embeddings_vector_hnsw",
        table_name="embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_embeddings_organization_id"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_asset_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index("uq_claim_metrics_pair", table_name="claim_metrics")
    op.drop_index(op.f("ix_claim_metrics_organization_id"), table_name="claim_metrics")
    op.drop_table("claim_metrics")
    op.drop_index(op.f("ix_metrics_project_id"), table_name="metrics")
    op.drop_index(op.f("ix_metrics_organization_id"), table_name="metrics")
    op.drop_table("metrics")
    op.drop_index("ix_claims_project_status", table_name="claims")
    op.drop_index(op.f("ix_claims_organization_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_activity_events_project_id"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_organization_id"), table_name="activity_events")
    op.drop_table("activity_events")
    op.drop_index(op.f("ix_search_queries_organization_id"), table_name="search_queries")
    op.drop_table("search_queries")
    # ### end Alembic commands ###
