"""before after pairs

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-28 17:09:10.934701+00:00

Phase 7. Before/after pairs (geometry, visible change, limitations, composite transformations and
the human decision) with row-level security, and evidence_links.pair_id so a confirmed pair can
support a claim. RESTRICT keeps a pair that evidence depends on from being deleted.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "before_after_pairs",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("before_asset_id", sa.UUID(), nullable=False),
        sa.Column("after_asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "analyzing",
                "analyzed",
                "failed",
                "confirmed",
                "rejected",
                name="pairstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum("suggested", "manual", name="pairorigin", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("days_apart", sa.Integer(), nullable=True),
        sa.Column("rank_score", sa.Float(), nullable=False),
        sa.Column("alignment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("analysis_version", sa.String(length=60), nullable=True),
        sa.Column("analysis_error", sa.Text(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("composite_transformation", sa.Text(), nullable=True),
        sa.Column("public_composite_transformation", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "before_asset_id <> after_asset_id", name=op.f("ck_before_after_pairs_distinct_assets")
        ),
        sa.ForeignKeyConstraint(
            ["after_asset_id"],
            ["assets.id"],
            name=op.f("fk_before_after_pairs_after_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["before_asset_id"],
            ["assets.id"],
            name=op.f("fk_before_after_pairs_before_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_before_after_pairs_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"], ["users.id"], name=op.f("fk_before_after_pairs_decided_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_before_after_pairs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_before_after_pairs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_before_after_pairs_site_id_sites"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_before_after_pairs")),
        sa.UniqueConstraint(
            "before_asset_id",
            "after_asset_id",
            name=op.f("uq_before_after_pairs_before_asset_id_after_asset_id"),
        ),
    )
    op.create_index(
        "ix_before_after_pairs_after", "before_after_pairs", ["after_asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_before_after_pairs_organization_id"),
        "before_after_pairs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_before_after_pairs_project_status",
        "before_after_pairs",
        ["project_id", "status"],
        unique=False,
    )
    op.add_column("evidence_links", sa.Column("pair_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_evidence_links_pair_id"), "evidence_links", ["pair_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_evidence_links_pair_id_before_after_pairs"),
        "evidence_links",
        "before_after_pairs",
        ["pair_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###

    op.execute("ALTER TABLE before_after_pairs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE before_after_pairs FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON before_after_pairs
        USING (
            current_setting('app.rls_bypass', true) = 'on'
            OR organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid
        )
        WITH CHECK (
            current_setting('app.rls_bypass', true) = 'on'
            OR organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON before_after_pairs")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_evidence_links_pair_id_before_after_pairs"), "evidence_links", type_="foreignkey"
    )
    op.drop_index(op.f("ix_evidence_links_pair_id"), table_name="evidence_links")
    op.drop_column("evidence_links", "pair_id")
    op.drop_index("ix_before_after_pairs_project_status", table_name="before_after_pairs")
    op.drop_index(op.f("ix_before_after_pairs_organization_id"), table_name="before_after_pairs")
    op.drop_index("ix_before_after_pairs_after", table_name="before_after_pairs")
    op.drop_table("before_after_pairs")
    # ### end Alembic commands ###
