"""initial schema: identity, projects/sites/taxonomies, assets, pipeline, observations, audit + RLS

Revision ID: 0001
Revises:
Create Date: 2026-09-24 17:26:00.537599+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# Frozen copy: a migration must never depend on the current code's table list.
TENANT_TABLES = (
    "projects",
    "sites",
    "taxonomies",
    "assets",
    "derivatives",
    "jobs",
    "analysis_runs",
    "observations",
    "audit_events",
)

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for ext in ("pgcrypto", "postgis", "vector"):
        op.execute(f"CREATE EXTENSION IF NOT EXISTS {ext}")

    op.create_table(
        "organizations",
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("external_id", name=op.f("uq_organizations_external_id")),
    )
    op.create_table(
        "users",
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_id", name=op.f("uq_users_external_id")),
    )
    op.create_table(
        "audit_events",
        sa.Column(
            "actor_kind",
            sa.Enum("user", "system", "webhook", name="actorkind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_target", "audit_events", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("run_key", sa.String(length=200), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed_retryable",
                "dead",
                name="jobstate",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("run_key", name=op.f("uq_jobs_run_key")),
    )
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_index("ix_jobs_target", "jobs", ["target_type", "target_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "viewer",
                "contributor",
                "reviewer",
                "manager",
                "admin",
                name="role",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("role_locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_memberships_organization_id_user_id")
        ),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("taxonomy_preset", sa.String(length=60), nullable=False),
        sa.Column("active_taxonomy_version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_projects_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_geospatial_table(
        "sites",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("radius_m", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            sa.Computed(
                "CASE WHEN latitude IS NULL OR longitude IS NULL THEN NULL ELSE (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326))::geography END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sites_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_sites_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("project_id", "code", name=op.f("uq_sites_project_id_code")),
    )
    op.create_geospatial_index(
        "ix_sites_location",
        "sites",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_sites_organization_id"), "sites", ["organization_id"], unique=False)
    op.create_index(op.f("ix_sites_project_id"), "sites", ["project_id"], unique=False)
    op.create_table(
        "taxonomies",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("activities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_taxonomies_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_taxonomies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_taxonomies_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomies")),
        sa.UniqueConstraint("project_id", "version", name=op.f("uq_taxonomies_project_id_version")),
    )
    op.create_index(
        op.f("ix_taxonomies_organization_id"), "taxonomies", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_taxonomies_project_id"), "taxonomies", ["project_id"], unique=False)
    op.create_geospatial_table(
        "assets",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("declared_activity", sa.String(length=48), nullable=True),
        sa.Column("declared_capture_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contributor_note", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column("declared_mime", sa.String(length=100), nullable=True),
        sa.Column("declared_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "resource_type",
            sa.Enum("image", "video", name="resourcetype", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("delivery_type", sa.String(length=20), nullable=False),
        sa.Column("public_id", sa.String(length=255), nullable=False),
        sa.Column("cloudinary_asset_id", sa.String(length=64), nullable=True),
        sa.Column("cloudinary_version", sa.BigInteger(), nullable=True),
        sa.Column("asset_folder", sa.String(length=512), nullable=True),
        sa.Column("format", sa.String(length=16), nullable=True),
        sa.Column("bytes", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("etag", sa.String(length=64), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("phash", sa.BigInteger(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capture_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "capture_time_source",
            sa.Enum(
                "exif",
                "device",
                "user",
                "upload",
                "site",
                "none",
                name="provenancesource",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "location_source",
            sa.Enum(
                "exif",
                "device",
                "user",
                "upload",
                "site",
                "none",
                name="provenancesource",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            sa.Computed(
                "CASE WHEN latitude IS NULL OR longitude IS NULL THEN NULL ELSE (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326))::geography END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("exif", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("media_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "awaiting_upload",
                "uploaded",
                "registered",
                "metadata_ready",
                "dedup_checked",
                "analyzing",
                "indexed",
                "review_required",
                "ready",
                "expired",
                "failed_retryable",
                "failed_permanent",
                name="assetstate",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("state_reason", sa.Text(), nullable=True),
        sa.Column("state_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("analysis_generation", sa.Integer(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("top_activity", sa.String(length=48), nullable=True),
        sa.Column("top_activity_confidence", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("review_priority", sa.Float(), nullable=True),
        sa.Column("review_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("exact_duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("near_duplicates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exact_duplicate_of_id"],
            ["assets.id"],
            name=op.f("fk_assets_exact_duplicate_of_id_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_assets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_assets_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_assets_site_id_sites"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"], ["users.id"], name=op.f("fk_assets_uploaded_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("cloudinary_asset_id", name=op.f("uq_assets_cloudinary_asset_id")),
        sa.UniqueConstraint("public_id", name=op.f("uq_assets_public_id")),
    )
    op.create_geospatial_index(
        "ix_assets_location",
        "assets",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index("ix_assets_org_sha256", "assets", ["organization_id", "sha256"], unique=False)
    op.create_index(op.f("ix_assets_organization_id"), "assets", ["organization_id"], unique=False)
    op.create_index(
        "ix_assets_project_capture", "assets", ["project_id", "capture_time"], unique=False
    )
    op.create_index("ix_assets_project_phash", "assets", ["project_id", "phash"], unique=False)
    op.create_index("ix_assets_project_state", "assets", ["project_id", "state"], unique=False)
    op.create_table(
        "analysis_runs",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "task",
            sa.Enum(
                "caption",
                "quality",
                "tagging",
                "vision_extract",
                "ocr",
                "auto_tagging",
                name="analysistask",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("model_version", sa.String(length=60), nullable=True),
        sa.Column("prompt_version", sa.String(length=80), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=40), nullable=True),
        sa.Column("taxonomy_version", sa.Integer(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("run_key", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running", "succeeded", "failed", name="runstatus", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_analysis_runs_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_analysis_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
        sa.UniqueConstraint("run_key", name=op.f("uq_analysis_runs_run_key")),
    )
    op.create_index(op.f("ix_analysis_runs_asset_id"), "analysis_runs", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_analysis_runs_organization_id"), "analysis_runs", ["organization_id"], unique=False
    )
    op.create_table(
        "derivatives",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("named_transformation", sa.String(length=80), nullable=True),
        sa.Column("transformation", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("generative", sa.Boolean(), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_derivatives_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_derivatives_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_derivatives_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_derivatives")),
    )
    op.create_index(op.f("ix_derivatives_asset_id"), "derivatives", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_derivatives_organization_id"), "derivatives", ["organization_id"], unique=False
    )
    op.create_table(
        "webhook_events",
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("notification_type", sa.String(length=60), nullable=True),
        sa.Column("public_id", sa.String(length=255), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("signature_scheme", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=60), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_webhook_events_asset_id_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_webhook_events_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_webhook_events_idempotency_key")),
    )
    op.create_index(
        op.f("ix_webhook_events_public_id"), "webhook_events", ["public_id"], unique=False
    )
    op.create_table(
        "observations",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("analysis_run_id", sa.UUID(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column(
            "ontology_type",
            sa.Enum(
                "scene",
                "activity",
                "object",
                "condition",
                "people",
                "document_text",
                "quality",
                "sensitive",
                name="ontologytype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("predicate", sa.String(length=60), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence_span", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "source_kind",
            sa.Enum("ai", "human", "system", name="sourcekind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("source_provider", sa.String(length=40), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "verified",
                "rejected",
                "superseded",
                name="observationstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("review_priority", sa.Float(), nullable=True),
        sa.Column("review_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_observations_analysis_run_id_analysis_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_observations_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_observations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_observations_reviewer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["observations.id"],
            name=op.f("fk_observations_supersedes_id_observations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
    )
    op.create_index(
        op.f("ix_observations_analysis_run_id"), "observations", ["analysis_run_id"], unique=False
    )
    op.create_index(
        "ix_observations_asset_type", "observations", ["asset_id", "ontology_type"], unique=False
    )
    op.create_index(
        op.f("ix_observations_organization_id"), "observations", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_observations_review",
        "observations",
        ["organization_id", "status", "review_priority"],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- Row-level security -------------------------------------------------------------
    # Tenant rows are visible only when app.current_org matches, or when system code explicitly
    # sets app.rls_bypass = 'on' (webhooks, workers). FORCE applies the policy to the table owner
    # too, so the app role cannot accidentally read across tenants.
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting('app.rls_bypass', true) = 'on'
                OR organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid
            )
            WITH CHECK (
                current_setting('app.rls_bypass', true) = 'on'
                OR organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid
            )
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")

    op.drop_index("ix_observations_review", table_name="observations")
    op.drop_index(op.f("ix_observations_organization_id"), table_name="observations")
    op.drop_index("ix_observations_asset_type", table_name="observations")
    op.drop_index(op.f("ix_observations_analysis_run_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_webhook_events_public_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_derivatives_organization_id"), table_name="derivatives")
    op.drop_index(op.f("ix_derivatives_asset_id"), table_name="derivatives")
    op.drop_table("derivatives")
    op.drop_index(op.f("ix_analysis_runs_organization_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_asset_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_index("ix_assets_project_state", table_name="assets")
    op.drop_index("ix_assets_project_phash", table_name="assets")
    op.drop_index("ix_assets_project_capture", table_name="assets")
    op.drop_index(op.f("ix_assets_organization_id"), table_name="assets")
    op.drop_index("ix_assets_org_sha256", table_name="assets")
    op.drop_geospatial_index(
        "ix_assets_location", table_name="assets", postgresql_using="gist", column_name="location"
    )
    op.drop_geospatial_table("assets")
    op.drop_index(op.f("ix_taxonomies_project_id"), table_name="taxonomies")
    op.drop_index(op.f("ix_taxonomies_organization_id"), table_name="taxonomies")
    op.drop_table("taxonomies")
    op.drop_index(op.f("ix_sites_project_id"), table_name="sites")
    op.drop_index(op.f("ix_sites_organization_id"), table_name="sites")
    op.drop_geospatial_index(
        "ix_sites_location", table_name="sites", postgresql_using="gist", column_name="location"
    )
    op.drop_geospatial_table("sites")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index("ix_jobs_target", table_name="jobs")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_audit_events_target", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
