"""reports and snapshots

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 05:35:48.812510+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ("reports", "report_snapshots")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "audience",
            sa.Enum("internal", "external", name="reportaudience", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column(
            "claim_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("narrative", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("narrative_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "published", name="reportstatus", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("latest_version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_reports_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_reports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_reports_site_id_sites"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_reports_project_id"), "reports", ["project_id"], unique=False)
    op.create_table(
        "report_snapshots",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("html_sha256", sa.String(length=64), nullable=False),
        sa.Column("renderer_version", sa.String(length=60), nullable=False),
        sa.Column("published_by_id", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "pdf_status",
            sa.Enum(
                "pending",
                "ready",
                "failed",
                "skipped",
                name="pdfstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("pdf_public_id", sa.String(length=512), nullable=True),
        sa.Column("pdf_bytes", sa.BigInteger(), nullable=True),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=True),
        sa.Column("pdf_error", sa.Text(), nullable=True),
        sa.Column("pdf_rendered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_report_snapshots_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_id"],
            ["users.id"],
            name=op.f("fk_report_snapshots_published_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_report_snapshots_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_snapshots")),
        sa.UniqueConstraint(
            "report_id", "version", name=op.f("uq_report_snapshots_report_id_version")
        ),
    )
    op.create_index(
        op.f("ix_report_snapshots_organization_id"),
        "report_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_snapshots_report_id"), "report_snapshots", ["report_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting('app.rls_bypass', true) = 'on'
                OR organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid
            )
            WITH CHECK (
                current_setting('app.rls_bypass', true) = 'on'
                OR organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid
            )
            """
        )

    # Published snapshots are immutable: only the PDF columns may be filled in afterwards.
    op.execute(
        """
        CREATE FUNCTION report_snapshot_immutable() RETURNS trigger AS $$
        BEGIN
            IF NEW.manifest IS DISTINCT FROM OLD.manifest
               OR NEW.manifest_sha256 IS DISTINCT FROM OLD.manifest_sha256
               OR NEW.html_sha256 IS DISTINCT FROM OLD.html_sha256
               OR NEW.renderer_version IS DISTINCT FROM OLD.renderer_version
               OR NEW.version IS DISTINCT FROM OLD.version
               OR NEW.report_id IS DISTINCT FROM OLD.report_id
               OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
               OR NEW.published_at IS DISTINCT FROM OLD.published_at
               OR NEW.published_by_id IS DISTINCT FROM OLD.published_by_id THEN
                RAISE EXCEPTION 'report snapshots are immutable';
            END IF;
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER report_snapshots_immutable BEFORE UPDATE ON report_snapshots "
        "FOR EACH ROW EXECUTE FUNCTION report_snapshot_immutable()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS report_snapshots_immutable ON report_snapshots")
    op.execute("DROP FUNCTION IF EXISTS report_snapshot_immutable()")
    for table in TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_snapshots_report_id"), table_name="report_snapshots")
    op.drop_index(op.f("ix_report_snapshots_organization_id"), table_name="report_snapshots")
    op.drop_table("report_snapshots")
    op.drop_index(op.f("ix_reports_project_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
